name: Build pull request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
      - compose-dev

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v3

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew assembleRelease --no-daemon

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: revanced-manager
          path: |
            app/build/outputs/apk/release/revanced-manager*.apk
            app/build/outputs/apk/release/revanced-manager*.apk.asc
